# Site settings
title: Data Science
email: albert.ys.kim@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Hello.
baseurl: /MATH216
url: https://rudeboybert.github.io
urllabel: "Albert Y. Kim's Webpage"

# Build settings
markdown: kramdown
github_username: rudeboybert
